/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import camm.*;
import ClassesSQL.VendaSQL;
import ClassesSQL.EstoqueSQL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import camm.Cliente;
import ClassesSQL.ClienteSQL;
import ClassesSQL.ItemVendaSQL;
import ClassesSQL.MaterialSQL;
import camm.Cliente;
import camm.Venda;
import camm.Estoque;
import camm.ItemVenda;
import camm.JtextFielSomenteNumeros;
import camm.JtextFielSomenteNumerosInteiros;
import camm.Material;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;

import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;


public class ManterVenda extends javax.swing.JFrame {

    /**
     * Creates new form ViewJTable
     */ 
     double valorTotalCompra = 0;
    double valorTotalVenda = 0;
    
    DecimalFormat df = new DecimalFormat("#,###.00"); 
    
    DecimalFormat df2 = new DecimalFormat("##,##0.000 Kg");
    DecimalFormat df1 = new DecimalFormat("##,##0 Unidades");
    
    public ManterVenda() {
        initComponents();
        this.setResizable(false);
        
        DefaultTableModel modelo = (DefaultTableModel) jTClientees.getModel();
        jTClientees.setRowSorter(new TableRowSorter(modelo));
        QuantidadeUsuario.setVisible(false);
        jTClientees.setDefaultRenderer(Object.class, new Centraliza());
           DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        
        jTClientees.getColumnModel().getColumn(3).setCellRenderer(direita);
        jTClientees.getColumnModel().getColumn(2).setCellRenderer(direita);
        jTClientees.getColumnModel().getColumn(1).setCellRenderer(direita);
        valorTo.setText("R$ 0.00");
        
        readComboBoxes();
        //readJTable();

    }
    
    public void readComboBoxes(){
        
        ClienteSQL fsql = new ClienteSQL();
        
        for(Cliente f: fsql.selectAllCliente()){
            comboF.addItem(f);
        }
        
         MaterialSQL msql = new MaterialSQL();
        
        for(Material m: msql.selectAllMaterial()){
            comboM.addItem(m);
        }
    }

    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTClientees.getModel();
        modelo.setNumRows(0);
        ItemVendaSQL csql = new ItemVendaSQL();
        

        for (ItemVenda ic : csql.selectAllItemVenda()) {

            modelo.addRow(new Object[]{
                ic.getCod_ItemVenda(),
                ic.getMaterial().getNome(),
                ic.getMaterial().getPreço_Kilo_Unidade(),
                ic.getPeso_Quantidade(),
                ic.getValorTotal(),
         
            });

        }

    }
    public void readJTableForDesc(String nome) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTClientees.getModel();
        modelo.setNumRows(0);
        ClienteSQL csql = new ClienteSQL();

        for (Cliente f : csql.selectForCliente(nome)) {
           
            
            modelo.addRow(new Object[]{
                f.getID_Cliente(),
                f.getNome(),
                f.getContato(),
                f.getBairro(),
                f.getLogradouro(),
                f.getNúmero()
            });
            
            

        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        comboM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PesoUsuario = new JtextFielSomenteNumeros(14);
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Observação = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        valorTo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboF = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientees = new javax.swing.JTable();
        QuantidadeUsuario = new JtextFielSomenteNumerosInteiros(14);
        jLabel7 = new javax.swing.JLabel();
        valorVenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        comboM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Material");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Peso / Quantidade");

        PesoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PesoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoUsuarioActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart_add.png"))); // NOI18N
        jButton5.setText("Finalizar Venda");
        jButton5.setMaximumSize(new java.awt.Dimension(109, 19));
        jButton5.setMinimumSize(new java.awt.Dimension(109, 19));
        jButton5.setPreferredSize(new java.awt.Dimension(109, 19));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Observação.setColumns(20);
        Observação.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Observação.setLineWrap(true);
        Observação.setRows(5);
        jScrollPane2.setViewportView(Observação);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Observação ");

        valorTo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Valor Total Pago");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButton1.setText("Incluir Item");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 31));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cliente");

        comboF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButton4.setText("Incluir Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTClientees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTClientees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Preço Unitário (R$)", "Peso / Quantidade (R$)", "Preço Item (R$)", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientees.setRowHeight(25);
        jTClientees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClienteesMouseClicked(evt);
            }
        });
        jTClientees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClienteesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientees);

        QuantidadeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Valor Recebido na Venda");

        valorVenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorVendaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Selecione um item para excluir");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cross.png"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(PesoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(QuantidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56)
                                .addComponent(comboF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorTo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(425, 425, 425))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(PesoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(valorTo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(valorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOVA VENDA");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jMenu10.setText("Cliente");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        jMenuItem1.setText("Adicionar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem3.setText("Consultar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem3);

        jMenuBar2.add(jMenu10);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart.png"))); // NOI18N
        jMenu13.setText("Compra");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart_add.png"))); // NOI18N
        jMenuItem5.setText("Adicionar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem5);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem7.setText("Consultar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem7);

        jMenuBar2.add(jMenu13);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/box.png"))); // NOI18N
        jMenu3.setText("Estoque");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem9.setText("Consultar Estoque");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem2.setText("Consultar Inventário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lorry.png"))); // NOI18N
        jMenu4.setText("Fornecedor ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lorry_add.png"))); // NOI18N
        jMenuItem10.setText("Adicionar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem11.setText("Consultar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar2.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow_refresh.png"))); // NOI18N
        jMenu5.setText("Material");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jMenuItem12.setText("Adicionar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem14.setText("Consultar");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuBar2.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_gray.png"))); // NOI18N
        jMenu6.setText("Usuário");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        jMenuItem16.setText("Adicionar");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem18.setText("Consultar");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuBar2.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money.png"))); // NOI18N
        jMenu7.setText("Venda");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money_add.png"))); // NOI18N
        jMenuItem20.setText("Adicionar");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem21.setText("Consultar");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        jMenuBar2.add(jMenu7);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book.png"))); // NOI18N
        jMenu9.setText("Relatório");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_add.png"))); // NOI18N
        jMenuItem4.setText("Adicionar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItem6.setText("Consultar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem6);

        jMenuBar2.add(jMenu9);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_out.png"))); // NOI18N
        jMenu8.setText("Sair");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        jMenuItem8.setText("Deslogar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        jMenuItem13.setText("Fechar CAMM");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem13);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTClienteesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClienteesMouseClicked
        // TODO add your handling code here:

        if (jTClientees.getSelectedRow() != -1) {

            PesoUsuario.setText(jTClientees.getValueAt(jTClientees.getSelectedRow(), 3).toString());
            
        }

    }//GEN-LAST:event_jTClienteesMouseClicked

    private void jTClienteesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClienteesKeyReleased
        // TODO add your handling code here:

        if (jTClientees.getSelectedRow() != -1) {

            PesoUsuario.setText(jTClientees.getValueAt(jTClientees.getSelectedRow(), 3).toString());
           

        }

    }//GEN-LAST:event_jTClienteesKeyReleased

    private void comboFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFActionPerformed

          
            
    }//GEN-LAST:event_comboFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0){
         int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
     if (reply == JOptionPane.YES_OPTION)
     {
        ManterCliente mf = new ManterCliente();
        mf.setVisible(true);
        this.dispose();
     }
     else{
         JOptionPane.getRootFrame().dispose();
     }
        }else{
            ManterCliente mf = new ManterCliente();
            mf.setVisible(true);
            this.dispose();
        }
        
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Tem certeza?", "Confirmação", JOptionPane.YES_NO_OPTION);
     if (reply == JOptionPane.YES_OPTION)
     {

        ItemVendaSQL icsql = new ItemVendaSQL();
        DefaultTableModel modelo = (DefaultTableModel) jTClientees.getModel();
        if(modelo.getRowCount()==0){
           JOptionPane.showMessageDialog(null, "Adicione pelo menos um item a venda");  
           return;
        }
        Venda c = new Venda();
        VendaSQL csql = new VendaSQL();

        EstoqueSQL esql = new EstoqueSQL();

        java.util.Date dt = new java.util.Date();
        java.text.SimpleDateFormat sdf =
        new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        sdf.setTimeZone(TimeZone.getTimeZone("GMT-3"));
        String currentTime = sdf.format(dt);
        if(comboF.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null, "Selecione um cliente");
          return;
        }
        c.setCliente((Cliente) comboF.getSelectedItem());
        if(valorVenda.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Adicione um valor à venda");  
          return;
        }
        c.setValorTotal(Double.parseDouble(valorVenda.getText()));

        csql.insertVenda(c,currentTime);

        Venda c1 = new Venda();
        c1.setCod_Venda(csql.selectLastInsert());

        for(int i=0;i<modelo.getRowCount();i++){

            try {
                ItemVenda ic = new ItemVenda();
                
                ic.setMaterial((Material)modelo.getValueAt(i, 0));
                String valoru = (String)modelo.getValueAt(i,1);
                NumberFormat format = NumberFormat.getInstance(Locale.US);
                Number number = format.parse(valoru);
                double u = number.doubleValue();
                ic.setValorUnitário(u);
                String digits = ((String)modelo.getValueAt(i,2)).replaceAll("[^0-9.]", "");
                ic.setPeso_Quantidade(Double.parseDouble(digits));
                String valort = (String)modelo.getValueAt(i,3);
                Number number1 = format.parse(valort);
                double t = number1.doubleValue();
                ic.setValorTotal(t);
                ic.setObservação((String)modelo.getValueAt(i, 4));
                ic.setVenda(c1);
                
                icsql.insertItemVenda(ic);
            } catch (ParseException ex) {
                Logger.getLogger(ManterVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        for(int j = 0;j<modelo.getRowCount();j++){
            Estoque e = new Estoque();
            Material m = (Material)modelo.getValueAt(j,0); 
            
            MaterialSQL msql = new MaterialSQL();
            e.setDataMovimetação(currentTime);
            e.setMaterial((Material)modelo.getValueAt(j,0));
            String digits = ((String)modelo.getValueAt(j,2)).replaceAll("[^0-9.]", "");
            e.setPeso_Quantidade(Double.parseDouble(digits));
            e.setTipoMovimentação("Venda");

            esql.insertEstoque(e);
            
            for(Material m1 : msql.selectForMaterialCod(m.getCod_Material())){
               
                if(m1.getTotal_estoque() < 0){
                    JOptionPane.showMessageDialog(null, "Material "+m.getNome()+" com saldo negativo");
                }
            }
        
        }
        ManterVenda cc = new ManterVenda();
        cc.setVisible(true);
        this.dispose();
     }else{
         JOptionPane.getRootFrame().dispose();
     }
        /*
        System.out.println("Material: "+ic.getMaterial().getNome());
        System.out.println("Valor Unitario "+ic.getValorUnitário());
        System.out.println("Observação: "+ic.getObservação());
        System.out.println("ValorTotal: "+ic.getValorTotal());*/

    }//GEN-LAST:event_jButton5ActionPerformed

    private void PesoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoUsuarioActionPerformed

    private void comboMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMActionPerformed
        // TODO add your handling code here:
        Material m = (Material)comboM.getSelectedItem();
        if(m.isPorQuantidade()){
            jLabel4.setText("Quantidade (Un.)");
            PesoUsuario.setVisible(false);
            QuantidadeUsuario.setVisible(true);
        }else{
            jLabel4.setText("Peso (Kg)");
            PesoUsuario.setVisible(true);
            QuantidadeUsuario.setVisible(false);
        }

    }//GEN-LAST:event_comboMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ItemVenda ic = new ItemVenda();
        ItemVendaSQL icsql = new ItemVendaSQL();
         if(comboM.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(null, "Selecione um material"); 
        }
        else{
        if(PesoUsuario.isVisible()){
            if(PesoUsuario.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Peso inválido");  
              return;
            }else{
        ic.setPeso_Quantidade(Double.parseDouble(PesoUsuario.getText()));}}
        else{
            if(QuantidadeUsuario.getText().equals("")){
       JOptionPane.showMessageDialog(null, "Quantidade inválida");  
       return;
            }else{
              ic.setPeso_Quantidade(Double.parseDouble(QuantidadeUsuario.getText()));   
            }
        }
        
        Material m = (Material) comboM.getSelectedItem();
        MaterialSQL msql = new MaterialSQL();
        
        for(Material m1 : msql.selectForMaterialCod(m.getCod_Material())){
            if(PesoUsuario.isVisible()){
            if((m1.getTotal_estoque() - (Double.parseDouble(PesoUsuario.getText()))) < 0){
                JOptionPane.showMessageDialog(null, "Quantidade de "+m1.getNome()+" indisponível em estoque");
                return;
            }
            }else{
              if((m1.getTotal_estoque() - (Double.parseDouble(QuantidadeUsuario.getText()))) < 0){
                JOptionPane.showMessageDialog(null, "Quantidade de "+m1.getNome()+" indisponível em estoque");
                return;  
            }
        }
        }
        
        ic.setMaterial((Material) comboM.getSelectedItem());
        ic.setValorUnitário(ic.getMaterial().getPreço_Kilo_Unidade());
        ic.setValorTotal(ic.getPeso_Quantidade()*ic.getValorUnitário());
        ic.setObservação(Observação.getText());
        DefaultTableModel modelo = (DefaultTableModel) jTClientees.getModel();
        String formatado;
        if(ic.getMaterial().isPorQuantidade()){
               
               formatado = df1.format(ic.getPeso_Quantidade());
            }else{
              
                formatado = df2.format(ic.getPeso_Quantidade());
            }
        modelo.addRow(new Object[]{

            ic.getMaterial(),
            df.format(ic.getValorUnitário()),
            formatado,
            df.format(ic.getValorTotal()),
            ic.getObservação()

        });

        PesoUsuario.setText(" ");
        Observação.setText(" ");
        QuantidadeUsuario.setText(" ");
        valorTotalVenda += ic.getValorTotal();
        valorTotalCompra += ic.getValorTotal();
       
        valorTo.setText("R$ "+df.format(valorTotalVenda));

        // }
        //readJTable();

        //        DefaultTableModel dtmProdutos = (DefaultTableModel) jTClientes.getModel();
        //        Object[] dados = {txtDesc.getText(), txtQtd.getText(), txtPreco.getText()};
        //        dtmProdutos.addRow(dados);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTClientees.getModel();
        if(jTClientees.getSelectedRow() != -1){
            try {
                String valor = ((String) jTClientees.getValueAt(jTClientees.getSelectedRow(),3));
                NumberFormat format = NumberFormat.getInstance(Locale.US);
                Number number = format.parse(valor);
                double d = number.doubleValue();
                valorTotalCompra -= d;
                modelo.removeRow(jTClientees.getSelectedRow());
                jTClientees.setModel(modelo);
                
                valorTo.setText("R$ "+df.format(valorTotalCompra));
                if(valorTotalCompra == 0){
                    valorTo.setText("R$ 0.00");
                }
            } catch (ParseException ex) {
                Logger.getLogger(ManterVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ManterCliente c = new ManterCliente();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ManterCliente c = new ManterCliente();
            c.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ConsultaCliente c = new ConsultaCliente();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ConsultaCliente c = new ConsultaCliente();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ManterCompra c = new ManterCompra();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ManterCompra c = new ManterCompra();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            try {
                ConsultaCompra c = new ConsultaCompra();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            try {
                ConsultaCompra c = new ConsultaCompra();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
          if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            try {
                TelaEstoque c = new TelaEstoque();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            try {
                TelaEstoque c = new TelaEstoque();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            try {
                ConsultaInventário c = new ConsultaInventário();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
           try {
               ConsultaInventário c = new ConsultaInventário();
               c.setVisible(true);
               this.dispose();
           } catch (ParseException ex) {
               Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
       if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ManterFornecedor c = new ManterFornecedor();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ManterFornecedor c = new ManterFornecedor();
            c.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add yo
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ConsultaFornecedor c = new ConsultaFornecedor();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ConsultaFornecedor c = new ConsultaFornecedor();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
         if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ManterMaterial c = new ManterMaterial();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ManterMaterial c = new ManterMaterial();
            c.setVisible(true);
            this.dispose();
        }
       
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ConsultaMaterial c = new ConsultaMaterial();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ConsultaMaterial c = new ConsultaMaterial();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
       if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ManterUsuário c = new ManterUsuário();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ManterUsuário c = new ManterUsuário();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
       if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ConsultaUsuário c = new ConsultaUsuário();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ConsultaUsuário c = new ConsultaUsuário();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            ManterVenda c = new ManterVenda();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            ManterVenda c = new ManterVenda();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            try {
                ConsultaVenda c = new ConsultaVenda();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            try {
                ConsultaVenda c = new ConsultaVenda();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            TelaRelatório c = new TelaRelatório();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            TelaRelatório c = new TelaRelatório();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            try {
                ConsultaRelatório c = new ConsultaRelatório();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            try {
                ConsultaRelatório c = new ConsultaRelatório();
                c.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(ManterCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            Login c = new Login();
            c.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            Login c = new Login();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         if(comboF.getSelectedIndex()>0 || comboM.getSelectedIndex() > 0 || !(PesoUsuario.getText().isEmpty()) || !(QuantidadeUsuario.getText().isEmpty()) || !(Observação.getText().isEmpty()) || jTClientees.getRowCount()>0 || !(valorVenda.getText().isEmpty())){
        
        int reply = JOptionPane.showConfirmDialog(null, "Os dados inseridos serão perdidos. Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }else{
            JOptionPane.getRootFrame().dispose();
        }
        }
        else{
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("ARIAL", Font.PLAIN, 16)));
        UIManager.put("OptionPane.messageForeground", Color.black);
        UIManager.put("OptionPane.buttonFont", new FontUIResource(new Font("ARIAL", Font.PLAIN, 15)));
        UIManager.put("OptionPane.background", Color.white);
        UIManager.put("Panel.background", Color.WHITE);
        JOptionPane.showMessageDialog(null,"Tela onde é possível adicionar uma nova Venda dentro do sistema.\n" +
"Primeiramente deve selecionar para qual Cliente será vendido (Se o Cliente não estiver cadastrado no sistema clique em “Incluir Cliente”),\nem seguida escolher qual material que está sendo vendido e sua respectiva quantidade ou peso.\nDepois disso o item já pode ser incluído na venda clicando em “Incluir Item”.\n" +
"Mais itens diferentes podem ser incluídos na Venda, e depois de cada inclusão o Valor Total Pago\né atualizado e deve-se preencher o valor que está sendo recebido na venda, para concluir a venda clique em “Finalizar Venda”.\n" +
"Se desejar excluir algum item basta selecioná-lo e clicar em “Excluir Item”.","Ajuda",3,null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void valorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterVenda().setVisible(true);
            }
        });
    }
    
    public JPanel retornaPainel(){
        return jPanel3; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Observação;
    private javax.swing.JTextField PesoUsuario;
    private javax.swing.JTextField QuantidadeUsuario;
    private javax.swing.JComboBox<Object> comboF;
    private javax.swing.JComboBox<Object> comboM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTClientees;
    private javax.swing.JLabel valorTo;
    private javax.swing.JTextField valorVenda;
    // End of variables declaration//GEN-END:variables
}
